encoding: utf-8
# baseurl可以不用设置,可通过{{site.baseurl}}获取,github-pages默认的根路径是Blog/_site/目录,所以这里可以不用设置
baseurl:
categories: javascript,css,html,mac,linux
#paginate: 5 # 指定每页多少条
#paginate_path: "page:num" # 指定每页的url
#markdown: macdown #默认使用macdown
