encoding: utf-8
# baseurl可以不用设置,可通过{{site.baseurl}}获取,github-pages默认的根路径是Blog/_site/目录,所以这里可以不用设置
baseurl:
categories: javascript,css,html,mac,linux

markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil
